Emdad/Models/SectorsServices.cs
using System;
using System.Collections.Generic;

namespace Emdad.Models;

public partial class SectorsServices : BaseEntity
{
    public int SectorsServicesId { get; set; }

    public string SectorsServicesName { get; set; } 

    public string SectorsServicesType { get; set; }

    public string SectorsServicesLink { get; set; }
    
    public int SectorsId { get; set; }

    public Sectors? Sectors { get; set; } 
}

Emdad/Areas/Admin/Controllers/SectorsServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Emdad.Models;

namespace Emdad.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SectorsServicesController : Controller
    {
        private readonly EmdadContext _context;

        public SectorsServicesController(EmdadContext context)
        {
            _context = context;
        }

        // GET: Admin/SectorsServices
        public async Task<IActionResult> Index()
        {
            var emdadContext = _context.SectorsServices.Include(s => s.Sectors);
            return View(await emdadContext.ToListAsync());
        }

        // GET: Admin/SectorsServices/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sectorsServices = await _context.SectorsServices
                .Include(s => s.Sectors)
                .FirstOrDefaultAsync(m => m.SectorsServicesId == id);
            if (sectorsServices == null)
            {
                return NotFound();
            }

            return View(sectorsServices);
        }

        // GET: Admin/SectorsServices/Create
        public IActionResult Create()
        {
            ViewData["SectorsId"] = new SelectList(_context.Sectors, "SectorsId", "SectorsId");
            return View();
        }

   
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SectorsServicesId,SectorsServicesName,SectorsServicesType,SectorsServicesLink,SectorsId,SectorsName,IsActive,IsDelete,CreateId,CreateDate,EditId,EditDate")] SectorsServices sectorsServices)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sectorsServices);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SectorsId"] = new SelectList(_context.Sectors, "SectorsId", "SectorsId", sectorsServices.SectorsId);
            return View(sectorsServices);
        }

        // GET: Admin/SectorsServices/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sectorsServices = await _context.SectorsServices.FindAsync(id);
            if (sectorsServices == null)
            {
                return NotFound();
            }
            ViewData["SectorsId"] = new SelectList(_context.Sectors, "SectorsId", "SectorsId", sectorsServices.SectorsId);
            return View(sectorsServices);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SectorsServicesId,SectorsServicesName,SectorsServicesType,SectorsServicesLink,SectorsId,SectorsName,IsActive,IsDelete,CreateId,CreateDate,EditId,EditDate")] SectorsServices sectorsServices)
        {
            if (id != sectorsServices.SectorsServicesId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(sectorsServices);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SectorsServicesExists(sectorsServices.SectorsServicesId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SectorsId"] = new SelectList(_context.Sectors, "SectorsId", "SectorsId", sectorsServices.SectorsId);
            return View(sectorsServices);
        }

        // GET: Admin/SectorsServices/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var sectorsServices = await _context.SectorsServices
                .Include(s => s.Sectors)
                .FirstOrDefaultAsync(m => m.SectorsServicesId == id);
            if (sectorsServices == null)
            {
                return NotFound();
            }

            return View(sectorsServices);
        }

        // POST: Admin/SectorsServices/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var sectorsServices = await _context.SectorsServices.FindAsync(id);
            if (sectorsServices != null)
            {
                _context.SectorsServices.Remove(sectorsServices);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SectorsServicesExists(int id)
        {
            return _context.SectorsServices.Any(e => e.SectorsServicesId == id);
        }
    }
}

Emdad/Controllers/FormFieldController.cs
using Emdad.Models.Repositories;
using Emdad.Models;
using Emdad.ViewModels;

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;

namespace Emdad.Controllers
{
    public class FormFieldController : Controller
    {
        // GET: FormFieldController
        private readonly IRepository<FormField> _repository;
        private readonly EmdadContext _context;

        public FormFieldController(IRepository<FormField> repository, EmdadContext context)
        {
            _repository = repository;
            _context = context;
        }

        // GET: FormFieldController
        public IActionResult Index(string name, int id)
        {
            var model = new FormFieldModel
            {
                ServiceId = id,
                Fields = _context.FormFields
        .Where(f => f.SectorsServicesId == id)
        .ToList()
            };
            return View(model);
        }

        // GET: SFormFieldController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: FormFieldController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SFormFieldController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormField collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    collection.CreateId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    collection.EditId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                    _repository.Add(collection);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Required values are missing.");
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: FormFieldController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: FormFieldController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FormFieldController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: FormFieldController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Emdad/Controllers/SectorsServicesController.cs
using Emdad.Models;
using Emdad.Models.Repositories;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace Emdad.Controllers
{
    public class SectorsServicesController : Controller
    {
        private readonly IRepository<SectorsServices> _repository;
        private readonly EmdadContext _context;

        public SectorsServicesController(IRepository<SectorsServices> repository, EmdadContext context)
        {
            _repository = repository;
            _context = context;
        }

        // GET: SectorsServicesController
        public IActionResult Index( int id)
        {
            var sector = _context.Sectors
       .FirstOrDefault(s => s.SectorsId == id);

            

            ViewBag.SectorName = sector.SectorsName;
            var services = _context.SectorsServices
    .Include(s => s.Sectors) // <- this is key
    .Where(s => s.SectorsId == id)
    .ToList();

            return View(services);
        }

        // GET: SectorsServicesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: SectorsServicesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SectorsServicesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SectorsServices collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    collection.CreateId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                    collection.EditId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

                    _repository.Add(collection);
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("", "Required values are missing.");
                    return View();
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: SectorsServicesController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: SectorsServicesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SectorsServicesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: SectorsServicesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Emdad/Views/SectorsServices/Index.cshtml
@model IEnumerable<Emdad.Models.SectorsServices>
@{
    ViewData["Title"] = "SectorsServices";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/assets/src/owl.carousel.min.css" />
    <link rel="stylesheet" href="~/assets/src/owl.theme.default.min.css" />
    <link rel="stylesheet" href="~/assets/src/style.css" />
    <!--  font-awesome -->
    <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
    <!-- end font-awesome -->
    <!-- fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@100..900&display=swap"
    rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
    rel="stylesheet" />
    <!-- end fonts -->

    <link href="~/assets/src/output.css" rel="stylesheet" />
</head>
<body class="font-sans">
    <nav class="w-full h-24"><special-header></special-header></nav>
    <div class="w-full h-[2px] bg-[#CEB579] mb-10"></div>
    <!-- بداية الخدمات -->
    <!-- start taps -->
    <div class="w-full flex justify-center items-center my-10">
        <p class="text-2xl font-bold">@ViewBag.SectorName</p>
    </div>
    <div class="w-full flex justify-center">
        <div class="w-4/5 px-10 py-10" style="box-shadow: 1px 1px 5px #ceb579">
            <div class="relative tab-group">
                <div class="flex bg-stone-100 p-0.5 relative justify-evenly rounded-lg"
                role="tablist">
                    <div class="absolute shadow-sm top-1 left-0.5 h-8 bg-white rounded-md transition-all duration-300 transform scale-x-0 translate-x-0 tab-indicator z-0"></div>
                    <a href="#"
                    class="tab-link items-center text-sm active inline-block py-2 px-4 text-stone-800 font-bold transition-all duration-300 relative z-1 mr-1"
                    data-dui-tab-target="tab1-group2">
                        الكل
                    </a>
                    <a href="#"
                    class="tab-link items-center text-sm inline-block py-2 px-4 text-stone-800 font-bold transition-all duration-300 relative z-1 mr-1"
                    data-dui-tab-target="tab2-group2">
                        شكوى
                    </a>
                    <a href="#"
                    class="tab-link items-center text-sm inline-block py-2 px-4 text-stone-800 font-bold transition-all duration-300 relative z-1 mr-1"
                    data-dui-tab-target="tab3-group2">
                        طلب
                    </a>
                </div>
                <div class="mt-4 tab-content-container">
                    <div id="tab1-group2" class="tab-content text-black block">
                        <p>عدد الخدمات المتوفرة @Model.Where(s => s.IsActive == true).Count()</p>
                        <div class="grid grid-rows-6 mt-5 gap-2">
                            @foreach (var item in Model)
                            {
                                <div class="sm:grid sm:grid-cols-9 mb-3 sm:border-b-2 flex flex-col-reverse items-center sm:shadow-none shadow-md w-full sm:h-full sm:py-0 py-5 sm:px-0 px-5">
                                    <button class="bg-[#ceb579] col-span-2 rounded-md text-white font-bold flex justify-center items-center w-4/5 h-fit sm:ml-0 py-1 my-1 px-1">
                                        @* <a href="/FormField/Index">
                                            @item.SectorsServicesType
                                        </a> *@
                                        <a class=" text-center"
                                        asp-controller="FormField"
                                        asp-action="Index"
                                        asp-route-name="@item.Sectors.SectorsName"
                                        asp-route-id="@item.SectorsServicesId">
                                            @item.SectorsServicesType
                                        </a>
                                    </button>
                                    <p class="flex sm:justify-end justify-center items-center col-span-7 w-full h-full font-medium sm:mb-0 mb-2">
                                        @item.SectorsServicesName
                                    </p>
                                </div>
                            }
                        </div>
                    </div>
                    <div id="tab2-group2" class="tab-content text-black hidden">
                        <p>عدد الخدمات المتوفرة @Model.Where(s => (s.IsActive == true)&&s.SectorsServicesType=="بلاغ").Count()</p>
                        <div class="grid grid-rows-6 mt-5 gap-2">
                            @foreach (var item in Model)
                            {
                                if (item.SectorsServicesType == "بلاغ") { 
                               
                                <div class="sm:grid sm:grid-cols-9 mb-3 sm:border-b-2 flex flex-col-reverse items-center sm:shadow-none shadow-md w-full sm:h-full sm:py-0 py-5 sm:px-0 px-5">
                                    <button class="bg-[#ceb579] col-span-2 rounded-md text-white font-bold flex justify-center items-center w-4/5 h-fit sm:ml-0 py-1 my-1 px-1">
                                        @* <a href="/FormField/Index">
                                            @item.SectorsServicesType
                                        </a> *@
                                        <a class=" text-center"
                                           asp-controller="FormField"
                                           asp-action="Index"
                                           asp-route-name="@item.Sectors.SectorsName"
                                           asp-route-id="@item.SectorsServicesId">
                                            @item.SectorsServicesType
                                        </a>
                                    </button>
                                    <p class="flex sm:justify-end justify-center items-center col-span-7 w-full h-full font-medium sm:mb-0 mb-2">
                                        @item.SectorsServicesName
                                    </p>
                                </div>
                                }
                            }
                        </div>
                    </div>
                    <div id="tab3-group2" class="tab-content text-black hidden">
                        <p>عدد الخدمات المتوفرة @Model.Where(s => (s.IsActive == true) && s.SectorsServicesType == "طلب").Count()</p>
                        <div class="grid grid-rows-6 mt-5 gap-2">
                            @foreach (var item in Model)
                            {
                                if (item.SectorsServicesType == "طلب")
                                {

                                    <div class="sm:grid sm:grid-cols-9 mb-3 sm:border-b-2 flex flex-col-reverse items-center sm:shadow-none shadow-md w-full sm:h-full sm:py-0 py-5 sm:px-0 px-5">
                                        <button class="bg-[#ceb579] col-span-2 rounded-md text-white font-bold flex justify-center items-center w-4/5 h-fit sm:ml-0 py-1 my-1 px-1">
                                            @* <a href="/FormField/Index">
                                            @item.SectorsServicesType
                                        </a> *@
                                            <a class=" text-center"
                                               asp-controller="FormField"
                                               asp-action="Index"
                                               asp-route-name="@item.Sectors.SectorsName"
                                               asp-route-id="@item.SectorsServicesId">
                                                @item.SectorsServicesType
                                            </a>
                                        </button>
                                        <p class="flex sm:justify-end justify-center items-center col-span-7 w-full h-full font-medium sm:mb-0 mb-2">
                                            @item.SectorsServicesName
                                        </p>
                                    </div>
                                }
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="flex justify-start items-center my-10 mx-10">
        <button class="bg-[#ceb579] rounded-lg text-lg font-medium px-2 py-1">
            <a href="./home_page.html#services">رجوع</a>
        </button>
    </div>
    <special-footer></special-footer>
    <!-- end taps-->
    <!-- نهاية الخدمات -->
    <script src="/assets/dist/template_pages.js"></script>
    <script src="/assets/dist/david-ai.min.js"></script>
</body>
</html>